# build stage
FROM node:lts-alpine as build-stage
COPY . /vuejs/
WORKDIR /vuejs
RUN npm install

# port
ARG VUEJS_PORT
ENV PORT=$VUEJS_PORT
EXPOSE $PORT

# development stage
CMD ["npm", "run", "serve"]